plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "blog/*/*"
    values:
      layout: "blog"
      title: "Neale Blog"
title: Neale Pickett
author:
  name: Neale Pickett
  uri: https://woozle.org/
