author:
  name: Neale Pickett
  email: neale@woozle.org
baseURL: https://woozle.org/
disablePathToLower: true
languageCode: en-us
title: Neale Pickett

enableGitInfo: true
markup:
  goldmark:
    renderer:
      unsafe: true

# This breaks inline images
#uglyurls: true

