author:
  name: Neale Pickett
  email: neale@woozle.org
baseURL: https://woozle.org/
disablePathToLower: true
languageCode: en-us
title: Neale Pickett
uglyurls: true
enableGitInfo: true
markup:
  goldmark:
    renderer:
      unsafe: true
