#! /bin/sh

while IFS=: read field value; do
    case "$field" in
        "")
            break
            ;;
        Title)
            # echo strips leading and trailing whitespace
            title=$(echo $value)
            ;;
    esac
done

markdown | m4 -DTITLE="$title" $1 -
