name: Homepage
on: [push]
jobs:
  build:
    runs-on:
      - hugo
    steps:
      - run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - run: hugo
      - name: set up SSH
        run: |
          mkdir -p $HOME/.ssh 
          cp .gitea/workflows/known_hosts $HOME/.ssh
          umask 077; cat > $HOME/.ssh/id_rsa <<EOD
          ${{ secrets.SSH_PUBLISH_PRIVATE_KEY }}
          EOD
          md5sum $HOME/.ssh/id_rsa
      - name: rsync
        run: |
          ssh-agent rsync --delete -vax ./public/ neale@melville.woozle.org:/srv/www/woozle.org/
