name: Homepage
on: [push]
jobs:
  build:
    container: klakegg/hugo:ext
    steps:
      - name: Check out source
        run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - name: Build
        run: hugo build
  publish:
    container: rsync/rsync
      - run: find
      - name: Publish
        run: rsync --delete -vax ./public/ neale@melville.woozle.org:/srv/www/woozle.org/
