name: Homepage
on: [push]
jobs:
  build:
    runs-on:
      - hugo
    steps:
      - name: Check out source
        run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - name: Build
        run: hugo
      - name: Publish
        run: rsync --delete -vax ./public/ neale@melville.woozle.org:/srv/www/woozle.org/
