name: Homepage
on: [push]
jobs:
  build:
    runs-on:
      - hugo
    timeout-minutes: 1
    steps:
      - run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - run: hugo
      - name: Set up SSH
        run: |
          mkdir -p $HOME/.ssh 
          cp .gitea/workflows/known_hosts $HOME/.ssh
          umask 077; cat > $HOME/.ssh/id_rsa <<EOD
          ${{ secrets.SSH_PUBLISH_PRIVATE_KEY }}
          EOD
          ls -l $HOME/.ssh
          md5sum $HOME/.ssh/id_rsa
      - run: |
          echo ssh-agent rsync --delete -vax ./public/ neale@melville.woozle.org:/srv/www/woozle.org/
